// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewPayment struct {
	OrderID         int32   `json:"orderId"`
	UserID          int32   `json:"userId"`
	Amount          float64 `json:"amount"`
	Currency        string  `json:"currency"`
	PaymentMethod   string  `json:"paymentMethod"`
	PaymentProvider *string `json:"paymentProvider,omitempty"`
}

type Payment struct {
	ID                   string  `json:"id"`
	OrderID              int32   `json:"orderId"`
	UserID               int32   `json:"userId"`
	Amount               float64 `json:"amount"`
	Currency             string  `json:"currency"`
	PaymentMethod        string  `json:"paymentMethod"`
	PaymentStatus        string  `json:"paymentStatus"`
	TransactionReference *string `json:"transactionReference,omitempty"`
	PaymentProvider      *string `json:"paymentProvider,omitempty"`
	PaidAt               *Time   `json:"paidAt,omitempty"`
	CreatedAt            *Time   `json:"createdAt,omitempty"`
	UpdatedAt            *Time   `json:"updatedAt,omitempty"`
}

type Query struct {
}
