// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type NewPayment struct {
	OrderID         int     `json:"orderId"`
	UserID          int     `json:"userId"`
	Amount          float64 `json:"amount"`
	Currency        string  `json:"currency"`
	PaymentMethod   string  `json:"paymentMethod"`
	PaymentProvider *string `json:"paymentProvider,omitempty"`
}

type Payment struct {
	ID                   int        `json:"id"`
	OrderID              int        `json:"orderId"`
	UserID               int        `json:"userId"`
	Amount               float64    `json:"amount"`
	Currency             string     `json:"currency"`
	PaymentMethod        string     `json:"paymentMethod"`
	PaymentStatus        string     `json:"paymentStatus"`
	PaymentProvider      *string    `json:"paymentProvider,omitempty"`
	PaidAt               *time.Time `json:"paidAt,omitempty"`
	CreatedAt            *time.Time `json:"createdAt,omitempty"`
	UpdatedAt            *time.Time `json:"updatedAt,omitempty"`
	TransactionReference string     `json:"transactionReference"`
}

type Query struct {
}

type VerifyPaymentInput struct {
	PaymentID       int    `json:"paymentId"`
	PaymentProvider string `json:"paymentProvider"`
	Credentials     string `json:"credentials"`
}
