// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	BasePrice   float64 `json:"basePrice"`
	Image       *string `json:"image,omitempty"`
}

type NewVariantInput struct {
	ProductID     string  `json:"productID"`
	VariantName   *string `json:"variantName,omitempty"`
	Size          *string `json:"size,omitempty"`
	Color         *string `json:"color,omitempty"`
	Price         float64 `json:"price"`
	StockQuantity int32   `json:"stockQuantity"`
}

type Product struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description *string           `json:"description,omitempty"`
	BasePrice   float64           `json:"basePrice"`
	Image       *string           `json:"image,omitempty"`
	CreatedAt   *string           `json:"createdAt,omitempty"`
	UpdatedAt   *string           `json:"updatedAt,omitempty"`
	Variants    []*ProductVariant `json:"variants"`
}

type ProductVariant struct {
	ID            string  `json:"id"`
	ProductID     string  `json:"productID"`
	VariantName   *string `json:"variantName,omitempty"`
	Size          *string `json:"size,omitempty"`
	Color         *string `json:"color,omitempty"`
	Price         float64 `json:"price"`
	StockQuantity int32   `json:"stockQuantity"`
	CreatedAt     *string `json:"createdAt,omitempty"`
	UpdatedAt     *string `json:"updatedAt,omitempty"`
}

type Query struct {
}

type UpdateProductInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	BasePrice   float64 `json:"basePrice"`
	Image       *string `json:"image,omitempty"`
}

type UpdateVariantInput struct {
	VariantName   *string `json:"variantName,omitempty"`
	Size          *string `json:"size,omitempty"`
	Color         *string `json:"color,omitempty"`
	Price         float64 `json:"price"`
	StockQuantity int32   `json:"stockQuantity"`
}
